Devcontainers & GHA Pipeline
sovrin-foundation/libsovtoken pull request #447
Opened 2022-08-31 12:08 UTC by pSchlarb

2022-08-31 12:34 UTC, WadeBarnes requested changes

2022-08-31 12:34 UTC, WadeBarnes commented on .github/workflows/Push.yaml
> +      - Gitpod
Should be removed.

2022-08-31 12:36 UTC, WadeBarnes commented on .github/workflows/Push.yaml
> +      - Gitpod
Remove GitPod

2022-08-31 20:19 UTC, WadeBarnes requested changes
Because we're planning on merging this into the stable branch we'll need to have the Jenkins build succeed as the gate.  The build is currently failing while trying to build a docker file

https://build.sovrin.org/blue/organizations/jenkins/libsovtoken%2Flibsovtoken-CI/detail/PR-447/3/pipeline/

![image](https://user-images.githubusercontent.com/10504350/187774200-c34ac3bd-745f-4f2b-928d-00be878f68d3.png)

2022-08-31 20:19 UTC, WadeBarnes commented on .github/workflows/Push.yaml
> +      - stable
This should include `master` and `stable`.  Sorry if our conversation was not clear before.

2022-10-12 14:11 UTC, WadeBarnes approved these changes

2022-10-17 15:10 UTC, pSchlarb commented on .github/workflows/Push.yaml
> +      - stable
Allow GHA to be run from Gitpod Branch
```suggestion
      - stable
      - Gitpod
```

2022-10-18 12:00 UTC, WadeBarnes approved these changes

2022-10-18 12:00 UTC, merged